package Vendedor;

import java.util.LinkedList;

import BaseDatos.Datos;
import BaseDatos.Productos;
import BaseDatos.Vendedores;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

/**Clase del controlador de la ventana eliminar vendedor
 * 
 * 
 *
 */
public class ventanaEliminarVendedorController {
	@FXML
	private Button regresarBtn;
	@FXML
	private TableView<Vendedores> tablaEliminarCliente;
	@FXML
	private TableColumn<Vendedores, String> credencialColumn;
	@FXML
	private TableColumn<Vendedores, String> nombreColumn;
	@FXML
	private TableColumn<Vendedores, String> apellidoColumn;
	@FXML
	private TableColumn<Vendedores, String> identificacionColumn;
	@FXML
	private TableColumn<Vendedores, String> fechaColumn;
	@FXML
	private TableColumn<Vendedores, String> contraseñaColumn;
	@FXML
	private Button visualizarBtn;
	@FXML
	private Button eliminarBtn;
	private Datos dataprovider = new Datos();
	private ObservableList<Vendedores> data = FXCollections.observableArrayList();

	// Event Listener on Button[#regresarBtn].onMouseClicked
	@FXML
	public void onRegresarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarBtn].onMouseClicked
	    /**Metodo para eliminar vendedores
	     * 
	     * @param event
	     */
		@FXML
		public void onEliminarClicked(MouseEvent event) {
			// TODO Autogenerated
			Vendedores todelete = this.tablaEliminarCliente.getSelectionModel().getSelectedItem();
			this.dataprovider.deleteVendedor(todelete);
			this.data.remove(todelete);
		}
	
	// Event Listener on Button[#visualizarBtn].onMouseClicked
	/**Metodo para mostrar los vendedores
	 * 	
	 * @param event
	 */
	@FXML
	public void onVisualizarClicked(MouseEvent event) {
		// TODO Autogenerated
		this.credencialColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("credencial"));
		this.identificacionColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("identificacion"));
		this.nombreColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("nombre"));
		this.apellidoColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("apellido"));
		this.fechaColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("fechaIngreso"));
		this.contraseñaColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("contrasena"));
		LinkedList<Vendedores> temp = this.dataprovider.getDatosVendedor();
		for(Vendedores item: temp) {
			this.data.add(item);
		}
		this.tablaEliminarCliente.setItems(data);
		
	}
	
}
