package Vendedor;

import java.util.LinkedList;

import BaseDatos.Datos;
import BaseDatos.Vendedores;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ventanaConsultarVendedorController {
	@FXML
	private Button regresarBtn;
	@FXML
	private TableView<Vendedores> tablaConsultarCliente;
	@FXML
	private TableColumn<Vendedores, String> credencialColumn;
	@FXML
	private TableColumn<Vendedores, String> nombreColumn;
	@FXML
	private TableColumn<Vendedores, String> apellidoColumn;
	@FXML
	private TableColumn<Vendedores, String> identificacionColumn;
	@FXML
	private TableColumn<Vendedores, String> fechaColumn;
	@FXML
	private TableColumn<Vendedores, String> contraseñaColumn;
	@FXML
	private Button consultarBtn;
	private Datos dataProvider = new Datos();
	private ObservableList<Vendedores> data = FXCollections.observableArrayList();

	// Event Listener on Button[#regresarBtn].onMouseClicked
	@FXML
	public void onRegresarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#consultarBtn].onMouseClicked
	@FXML
	public void onConsultarClicked(MouseEvent event) {
		// TODO Autogenerated
		this.credencialColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("credencial"));
		this.identificacionColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("id"));
		this.nombreColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("nombre"));
		this.apellidoColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("apellido"));
		this.fechaColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("fechaIngreso"));
		this.contraseñaColumn.setCellValueFactory(new PropertyValueFactory<Vendedores, String>("contrasena"));
		LinkedList<Vendedores> temp = this.dataProvider.getDatosVendedor();
		for(Vendedores item: temp) {
			this.data.add(item);
		}
		this.tablaConsultarCliente.setItems(data);
		
	}
	
}

