package Vendedor;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ventanaUpdateVendedorController {
	@FXML
	private Button regresarBtn;
	@FXML
	private TableView<?> tablaAñadirCliente;
	@FXML
	private TableColumn<?, ?> credencialColumn;
	@FXML
	private TableColumn<?, ?> nombreColumn;
	@FXML
	private TableColumn<?, ?> apellidoColumn;
	@FXML
	private TableColumn<?, ?> identificacionColumn;
	@FXML
	private TableColumn<?, ?> tipoIdColumn;
	@FXML
	private TextField credencialTxt;
	@FXML
	private TextField nombreTxt;
	@FXML
	private TextField apellidoTxt;
	@FXML
	private TextField identificacionTxt;
	@FXML
	private TextField tipoIdTxt;
	@FXML
	private Button modificarBtn;
	@FXML
	private TextField credencialBuscarTxt;
	@FXML
	private Button visualizarBtn;

	// Event Listener on Button[#regresarBtn].onMouseClicked
	@FXML
	public void onRegresarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modificarBtn].onMouseClicked
	@FXML
	public void onModificarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#visualizarBtn].onMouseClicked
	@FXML
	public void onVisualizarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
