package Presentacion;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

public class popUpAñadirProductoController {
	@FXML
	private Button xButton;
	@FXML
	private Button añadirBtn;
	@FXML
	private Button generarBtn;

	// Event Listener on Button[#xButton].onMouseClicked
	@FXML
	public void onXClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#añadirBtn].onMouseClicked
	@FXML
	public void onAñadirClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#generarBtn].onMouseClicked
	@FXML
	public void onGenerarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
