package Presentacion;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

/**Clase del controlador de la ventana que muestra las opciones de la aplicacion
 * 
 * 
 *
 */
public class ventanaOpcionesController {
	@FXML
	private Button registrarFacturaBtn;
	@FXML
	private Button consultarFacturaBtn;
	@FXML
	private Button eliminarFacturaBtn;
	@FXML
	private Button añadirProductoBtn;
	@FXML
	private Button consultarProductoBtn;
	@FXML
	private Button modificarProductoBtn;
	@FXML
	private Button eliminarProductoBtn;
	@FXML
	private Button añadirVendedor;
	@FXML
	private Button consultarVendedorBtn;
	@FXML
	private Button modificarVendedorBtn;
	@FXML
	private Button eliminarVendedorBtn;
	@FXML
	private Button ventasPorProductoBtn;
	@FXML
	private Button comisionesBtn;

	// Event Listener on Button[#registrarFacturaBtn].onMouseClicked
	/**Metodo que carga la ventana generar factura
	 * 
	 * @param event
	 */
	@FXML
	public void onRegistrarFacturaClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource("/Facturas/ventanaGenerarFactura.fxml"));
			Scene scene = new Scene(root);
			Stage st = new Stage();
			st.setScene(scene);
			st.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#consultarFacturaBtn].onMouseClicked
	@FXML
	public void onConsultarFacturaClicked(MouseEvent event) {
		// TODO Autogenerated
		
	}
	// Event Listener on Button[#eliminarFacturaBtn].onMouseClicked
	@FXML
	public void onEliminarFacturaClicked(MouseEvent event) {
		// TODO Autogenerated
		
	}
	// Event Listener on Button[#a�adirProductoBtn].onMouseClicked
	/**Metodo que carga la ventana añadir producto
	 * 
	 * @param event
	 */
	@FXML
	public void onAñadirProductoClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource("/Producto/ventanaAñadirProducto.fxml"));
			Scene scene = new Scene(root);
			Stage st = new Stage();
			st.setScene(scene);
			st.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#consultarProductoBtn].onMouseClicked
	/**Metodo que carga la ventana consultar producto
	 * 
	 * @param event
	 */
	@FXML
	public void onConsultarProductoClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource("/Producto/ventanaConsultarProducto.fxml"));
			Scene scene = new Scene(root);
			Stage st = new Stage();
			st.setScene(scene);
			st.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#modificarProductoBtn].onMouseClicked
	@FXML
	public void onModificarProductoClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarProductoBtn].onMouseClicked
	/**Metodo que carga la ventana eliminar producto
	 * 
	 * @param event
	 */
	@FXML
	public void onEliminarProductoClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource("/Producto/ventanaEliminarProducto.fxml"));
			Scene scene = new Scene(root);
			Stage st = new Stage();
			st.setScene(scene);
			st.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#a�adirVendedor].onMouseClicked
	/**Metodo que carga la ventana añadir vendedor
	 * 
	 * @param event
	 */
	@FXML
	public void onAñadirVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource("/Vendedor/ventanaAñadirVendedor.fxml"));
			Scene scene = new Scene(root);
			Stage st = new Stage();
			st.setScene(scene);
			st.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#consultarVendedorBtn].onMouseClicked
	/**Metodo que carga la ventana consultar vendedor
	 * 
	 * @param event
	 */
	@FXML
	public void onConsultarVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource("/Vendedor/ventanaConsultarVendedor.fxml"));
			Scene scene = new Scene(root);
			Stage st = new Stage();
			st.setScene(scene);
			st.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#modificarVendedorBtn].onMouseClicked
	@FXML
	public void onModificarVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarVendedorBtn].onMouseClicked
	/**Metodo que carga la ventana eliminar vendedor
	 * 
	 * @param event
	 */
	@FXML
	public void onEliminarVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource("/Vendedor/ventanaEliminarVendedor.fxml"));
			Scene scene = new Scene(root);
			Stage st = new Stage();
			st.setScene(scene);
			st.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#ventasPorProductoBtn].onMouseClicked
	@FXML
	public void onVentasPorProductoClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#comisionesBtn].onMouseClicked
	@FXML
	public void onComisionesClicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
