package Presentacion;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ventanaUpdateFacturaProductoController {
	@FXML
	private Button regresarBtn;
	@FXML
	private TableView<?> tablaProducto;
	@FXML
	private TableColumn<?, ?> cantidadColumn;
	@FXML
	private TableColumn<?, ?> referenciaColumn;
	@FXML
	private TableColumn<?, ?> productoColumn;
	@FXML
	private TableColumn<?, ?> tipoColumn;
	@FXML
	private TableColumn<?, ?> tipoProductoColumn;
	@FXML
	private TableColumn<?, ?> impuestoColumn;
	@FXML
	private TableColumn<?, ?> valorColumn;
	@FXML
	private TextField referenciaTxt;
	@FXML
	private Button añadirBtn;
	@FXML
	private Button eliminarBtn;

	// Event Listener on Button[#regresarBtn].onMouseClicked
	@FXML
	public void onRegresarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#añadirBtn].onMouseClicked
	@FXML
	public void onAñadirClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarBtn].onMouseClicked
	@FXML
	public void onEliminarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
