package Presentacion;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class ventanaLoginController {
	@FXML
	private TextField usuarioTxt;
	@FXML
	private TextField credencialTxt;
	@FXML
	private Button entrarBtn;

	// Event Listener on Button[#entrarBtn].onMouseClicked
	@FXML
	public void onEntrarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
