package Presentacion;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javafx.stage.Window;

public class ventanaOpcionesVendedorController {
	@FXML
	private Button registrarFacturaBtn;
	@FXML
	private Button consultarFacturaBtn;
	@FXML
	private Button eliminarFacturaBtn;
	 @FXML
	private Button btnRegresar;
	// Event Listener on Button[#registrarFacturaBtn].onMouseClicked
	/**Funcion que recibe un clic como evento para abrir: ventanaRegistrarFactura
	* 
	* @param event
	*/	
	@FXML
	public void onRegistrarFacturaClicked(MouseEvent event) {
	    // TODO Autogenerated
	    Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Facturas/VentanaRegistrarFactura.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
	}

	// Event Listener on Button[#consultarFacturaBtn].onMouseClicked
	
	/**Funcion que recibe un clic como evento para abrir: ventanaConsultaFactura
	* @param event
	*/	
	@FXML
	public void onConsultarFacturaClicked(MouseEvent event) {
		
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Facturas/ventanaConsultaFactura.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarFacturaBtn].onMouseClicked
	
	/**Funcion que recibe un clic como evento para abrir: ventanaEliminarFactura
	* 
	* @param event
	*/	
	@FXML
	public void onEliminarFacturaClicked(MouseEvent event) {
		
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Facturas/ventanaEliminarFactura.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
		// TODO Autogenerated
	}
	
	/**Funcion que recibe un clic como evento para abrir: ventanaOpcionesVendedor
	* 
	* @param event
	*/	
	@FXML
    void onRegresarClicked(MouseEvent event) {

		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Presentacion/ventanaLogin.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
    }
}
