package Presentacion;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

/**Clase del controlador de la ventana que muestra las opciones de la aplicacion
 * 
 * 
 *
 */
public class ventanaOpcionesController {
	
	
	
	@FXML
	private Button añadirProductoBtn;
	@FXML
	private Button modificarProductoBtn;
	@FXML
	private Button eliminarProductoBtn;
	@FXML
	private Button añadirVendedor;
	@FXML
	private Button consultarVendedorBtn;
	@FXML
	private Button eliminarVendedorBtn;
	@FXML
	private Button ventasPorProductoBtn;
	@FXML
	private Button comisionesBtn;
	@FXML
	private Button btnRegresar;

	
	
	
	// Event Listener on Button[#a�adirProductoBtn].onMouseClicked
	/**Metodo que carga la ventana añadir producto
	 * 
	 * @param event
	 */
	@FXML
	public void onAñadirProductoClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("Producto/venatanaAñadirProducto.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Titulo de la ventana
	        newStage.setTitle("WowGames: AñadirProducto");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
	}
	
	// Event Listener on Button[#modificarProductoBtn].onMouseClicked
	/**Metodo que carga la ventana: ventanaModificarProducto
	 * 
	 * @param event
	 */
	@FXML
	public void onModificarProductoClicked(MouseEvent event) {
		
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Producto/ventanaModificarProducto.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Titulo de la ventana
	        newStage.setTitle("WowGames: ModificarProducto");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
		// TODO Autogenerated
	}
	
	
	// Event Listener on Button[#eliminarProductoBtn].onMouseClicked
	/**Metodo que carga la ventana eliminar producto
	 * 
	 * @param event
	 */
	@FXML
	public void onEliminarProductoClicked(MouseEvent event) {
		
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Producto/ventanaEliminarProducto.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	     // Titulo de la ventana
	        newStage.setTitle("WowGames: EliminarProducto");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
		// TODO Autogenerated
	}
	
	
	// Event Listener on Button[#a�adirVendedor].onMouseClicked
	/**Metodo que carga la ventana añadir vendedor
	 * 
	 * @param event
	 */
	@FXML
	public void onAñadirVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Vendedor/ventanaAñadirVendedor.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Titulo de la ventana
	        newStage.setTitle("WowGames: AñadirVendedor");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
	}
	
	
	// Event Listener on Button[#consultarVendedorBtn].onMouseClicked
	/**Metodo que carga la ventana consultar vendedor
	 * 
	 * @param event
	 */
	@FXML
	public void onConsultarVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Vendedor/ventanaConsultarVendedor.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Titulo de la ventana
	        newStage.setTitle("WowGames: ConsultarVendedor");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
	}
	
	
	// Event Listener on Button[#eliminarVendedorBtn].onMouseClicked
	/**Metodo que carga la ventana eliminar vendedor
	 * 
	 * @param event
	 */
	@FXML
	public void onEliminarVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Vendedor/ventanaEliminarVendedor.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Titulo de la ventana
	        newStage.setTitle("WowGames: EliminarVendedor");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
	}
	// Event Listener on Button[#ventasPorProductoBtn].onMouseClicked
	/**Metodo que carga la ventana: ventanaVentasPorProducto
	 * 
	 * @param event
	 */
	@FXML
	public void onVentasPorProductoClicked(MouseEvent event) {
		
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Producto/ventanaVentasPorProducto.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Titulo de la ventana
	        newStage.setTitle("WowGames: VentasPorProducto");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
		// TODO Autogenerated
	}
	
	
	// Event Listener on Button[#comisionesBtn].onMouseClicked
	/**Metodo que carga la ventana: ventanaComisiones
	 * 
	 * @param event
	 */
	@FXML
	public void onComisionesClicked(MouseEvent event) {
		
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Vendedor/ventanaComisiones.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Titulo de la ventana
	        newStage.setTitle("WowGames: Comisiones");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
		// TODO Autogenerated
	}
	
	@FXML
    void onRegresarClicked(MouseEvent event) {

		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Presentacion/ventanaLogin.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        // Titulo de la ventana
	        newStage.setTitle("WowGames: VentanaLogin");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
    }
}
