package Presentacion;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

public class ventanaOpcionesController {
	@FXML
	private Button registrarFacturaBtn;
	@FXML
	private Button consultarFacturaBtn;
	@FXML
	private Button eliminarFacturaBtn;
	@FXML
	private Button añadirProductoBtn;
	@FXML
	private Button consultarProductoBtn;
	@FXML
	private Button modificarProductoBtn;
	@FXML
	private Button eliminarProductoBtn;
	@FXML
	private Button añadirVendedor;
	@FXML
	private Button consultarVendedorBtn;
	@FXML
	private Button modificarVendedorBtn;
	@FXML
	private Button eliminarVendedorBtn;
	@FXML
	private Button ventasPorProductoBtn;
	@FXML
	private Button comisionesBtn;

	// Event Listener on Button[#registrarFacturaBtn].onMouseClicked
	@FXML
	public void onRegistrarFacturaClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#consultarFacturaBtn].onMouseClicked
	@FXML
	public void onConsultarFacturaClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarFacturaBtn].onMouseClicked
	@FXML
	public void onEliminarFacturaClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#a�adirProductoBtn].onMouseClicked
	@FXML
	public void onAñadirProductoClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#consultarProductoBtn].onMouseClicked
	@FXML
	public void onConsultarProductoClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modificarProductoBtn].onMouseClicked
	@FXML
	public void onModificarProductoClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarProductoBtn].onMouseClicked
	@FXML
	public void onEliminarProductoClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#a�adirVendedor].onMouseClicked
	@FXML
	public void onAñadirVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#consultarVendedorBtn].onMouseClicked
	@FXML
	public void onConsultarVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modificarVendedorBtn].onMouseClicked
	@FXML
	public void onModificarVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#eliminarVendedorBtn].onMouseClicked
	@FXML
	public void onEliminarVendedorClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ventasPorProductoBtn].onMouseClicked
	@FXML
	public void onVentasPorProductoClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#comisionesBtn].onMouseClicked
	@FXML
	public void onComisionesClicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
