package Presentacion;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class ventanaGenerarFacturaController {
	@FXML
	private TextField nombreTxt;
	@FXML
	private TextField direccionTxt;
	@FXML
	private TextField apellidoTxt;
	@FXML
	private TextField identificacionTxt;
	@FXML
	private TextField fechaTxt;
	@FXML
	private TextField telefonoTxt;
	@FXML
	private Button registrarBtn;
	@FXML
	private Button regresarBtn;

	// Event Listener on Button[#registrarBtn].onMouseClicked
	@FXML
	public void onRegistrarBtn(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
    void onRegresarClicked(MouseEvent event) {

    }
}
