package Presentacion;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class ventanaLoginController {
	@FXML
	private TextField usuarioTxt;
	@FXML
	private TextField credencialTxt;
	@FXML
	private Button entrarBtn;

	// Event Listener on Button[#entrarBtn].onMouseClicked
	@FXML
	public void onEntrarClicked(MouseEvent event) {
		// TODO Autogenerated
		Parent root;
		try {
			root = FXMLLoader.load(getClass().getResource("/Presentacion/ventanaOpciones.fxml"));
			Scene scene = new Scene(root);
			Stage st = new Stage();
			st.setScene(scene);
			st.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
