package Facturas;

import java.awt.event.ActionEvent;

import BaseDatos.Datos;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

/**Clase del controlador de la ventana update factura
 * 
 * 
 *
 */
public class ventanaUpdateFacturaClienteController {
	@FXML
	private Button regresarBtn;
	@FXML
	private TableView<?> tablaCliente;
	@FXML
	private TableColumn<?, ?> nombreColumn;
	@FXML
	 private TableColumn<?, ?> apellidoColumn;
	@FXML
	private TableColumn<?, ?> direccionColumn;
	@FXML
	private TableColumn<?, ?> telefonoColumn;
	@FXML
	private TableColumn<?, ?> identificacionColumn;
	@FXML
	private TextField nombreTxt;
	@FXML
	private TextField apellidoTxt;
	@FXML
	private TextField identificacionTxt;
	@FXML
	private TextField direccionTxt;
	@FXML
	private TextField fechaTxt;
	@FXML
	private TextField telefonoTxt;
	@FXML
	private Button modificarBtn;
	
	@FXML
	void editApellido(ActionEvent event) {

		
		
		////agg fecha 
	    }

	@FXML
	void editDireccion(ActionEvent event) {

		
		Datos datos = new Datos();
		boolean exito = gestorClientes.updateCliente(cliente);
		
	    }

	@FXML
	void editIdentificación(ActionEvent event) {

	    }

	@FXML
	void editNombre(ActionEvent event) {

	    }

	@FXML
	void editTelefono(ActionEvent event) {

	    }

	// Event Listener on Button[#regresarBtn].onMouseClicked
	@FXML
	public void onRegresarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modificarBtn].onMouseClicked
	@FXML
	public void onModificarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
