package Facturas;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import BaseDatos.Clientes;
import BaseDatos.Datos;
import BaseDatos.Facturas;
import BaseDatos.Productos;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.CheckBox;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ventanaRegistrarFacturaController {
	@FXML
	private TextField codigoProductoTxt;
	@FXML
	private TableView<?> registrarVentaTable;
	@FXML
	private TableColumn<?, ?> credencialColumn;
	@FXML
	private TableColumn<?, ?> codigoProductoColumn;
	@FXML
	private TableColumn<?, ?> tipoColumn;
	@FXML
	private TableColumn<?, ?> nombreProductoColumn;
	@FXML
	private TableColumn<?, ?> plataformaColumn;
	@FXML
	private TableColumn<?, ?> precioColumn;
	@FXML
	private Button ingresarBtn;
	@FXML
	private Button regresarBtn;
	@FXML
	private CheckBox descuentoBox;
	@FXML
	private Button generarFacturaBtn;
	
	private Datos dataProvider = new Datos();
	
	
	private float id; 
	private String fecha;
	private float subtotal;
	private float valorTotal;
	private float descuento;
	private String crendencialVendedor;
	private String identificacionCliente;
	private Float idFac = null;
	

	// Event Listener on TableView[#registrarVentaTable].onMouseClicked
	@FXML
	public void onSelection(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ingresarBtn].onMouseClicked
	@FXML
	public void onIngresarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#regresarBtn].onMouseClicked
	@FXML
	public void onRegresarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	
	
	
	
	
	// Event Listener on Button[#generarFacturaBtn].onMouseClicked
	@FXML
	public void onGenerarClicked(MouseEvent event) {
		// TODO Autogenerated
		
		
		//se genera automaticamente el ID de cada factura
	if(idFac == null) {
				idFac = (float) 1;
			}else {
				Datos datos = new Datos(); 
		        Facturas resultado = null;
		        resultado = datos.consultarId(resultado);
		        
		        idFac = resultado.getId() + 1; 
			}
		
		//se calcula la fecha
		LocalDate fechaActual = LocalDate.now();
    	DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy");
	    String fecha = fechaActual.format(formato);
		
	    //se calcula el subtotal
	    	Datos datos3 = new Datos();
	    		Productos resultado3 = null;
	    resultado3 = datos3.updateCliente(resultado3);
	    
		Facturas nuevo = new Facturas(idFac, fecha, subtotal, valorTotal,descuento, crendencialVendedor, identificacionCliente );
		boolean success = this.dataProvider.createFactura(nuevo);
		if (success) {
			Alert alt = new Alert(Alert.AlertType.INFORMATION);
			alt.setContentText("Factura Creada");
			alt.setHeaderText("Creado");
			alt.show();
		}else {
			Alert alt = new Alert(Alert.AlertType.ERROR);
			alt.setContentText("Error al crear el factura");
			alt.setHeaderText("Error");
			alt.show();
		}
		
		
	}
}
