package Facturas;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

/**Clase del controlador de la ventana update factura
 * 
 * 
 *
 */
public class ventanaUpdateFacturaClienteController {
	@FXML
	private Button regresarBtn;
	@FXML
	private TableView<?> tablaCliente;
	@FXML
	private TableColumn<?, ?> nombreColumn;
	@FXML
	private TableColumn<?, ?> idColumn;
	@FXML
	private TableColumn<?, ?> direccionColumn;
	@FXML
	private TableColumn<?, ?> telefonoColumn;
	@FXML
	private TableColumn<?, ?> vendedorColumn;
	@FXML
	private TextField nombreTxt;
	@FXML
	private TextField apellidoTxt;
	@FXML
	private TextField identificacionTxt;
	@FXML
	private TextField direccionTxt;
	@FXML
	private TextField fechaTxt;
	@FXML
	private TextField telefonoTxt;
	@FXML
	private Button modificarBtn;

	// Event Listener on Button[#regresarBtn].onMouseClicked
	@FXML
	public void onRegresarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#modificarBtn].onMouseClicked
	@FXML
	public void onModificarClicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
