package Facturas;

import BaseDatos.Clientes;
import BaseDatos.Datos;
import BaseDatos.Facturas;
import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class ventanaGenerarFacturaController {
	@FXML
	private TextField credencialTxt;
	@FXML
	private TextField nombreTxt;
	@FXML
	private TextField direccionTxt;
	@FXML
	private TextField apellidoTxt;
	@FXML
	private TextField identificacionTxt;
	@FXML
	private TextField fechaTxt;
	@FXML
	private TextField telefonoTxt;
	@FXML
	private Button registrarBtn;
	@FXML
	private Button regresarBtn;

	@FXML
	private Button generarBtn;
	private Datos dataProvider = new Datos();
	private Float descuento = (float) 0.2;
	private Float subTotal = (float)0;
	private Float valorTotal = (float)0;
	private Float idFac = null;
	float id;
	int i = 1;

	// Event Listener on Button[#registrarBtn].onMouseClicked
	@FXML
	public void onRegistrarBtn(MouseEvent event) {
		// TODO Autogenerated
		Clientes nuevo = new Clientes(identificacionTxt.getText(), nombreTxt.getText(), apellidoTxt.getText(), fechaTxt.getText(), direccionTxt.getText(), telefonoTxt.getText());
		boolean success = this.dataProvider.createCliente(nuevo);
		if (success) {
			Alert alt = new Alert(Alert.AlertType.INFORMATION);
			alt.setContentText("Usuario Creado");
			alt.setHeaderText("Creado");
			alt.show();
		}else {
			Alert alt = new Alert(Alert.AlertType.ERROR);
			alt.setContentText("Error Creando el usuario");
			alt.setHeaderText("error");
			alt.show();
		}
	}
	
	@FXML
    void onGenerarClicked(MouseEvent event) {
		
		if(idFac == null) {
			idFac = (float) 1;
		}else {
			Datos datos = new Datos(); 
	        Facturas resultado = null;
	        resultado = datos.consultarId(resultado);
	        
	        id = resultado.getId() + 1; 
	        idFac = id;
		}
			
		
		
		
		Facturas nuevo = new Facturas(idFac, fechaTxt.getText(), subTotal, valorTotal, descuento, credencialTxt.getText(), identificacionTxt.getText());
		boolean success = this.dataProvider.createFactura(nuevo);
		if (success) {
			Alert alt = new Alert(Alert.AlertType.INFORMATION);
			alt.setContentText("Usuario Creado");
			alt.setHeaderText("Creado");
			alt.show();
		}else {
			Alert alt = new Alert(Alert.AlertType.ERROR);
			alt.setContentText("Error Creando el usuario");
			alt.setHeaderText("error");
			alt.show();
		}

    }
	
	
	@FXML
    void onRegresarClicked(MouseEvent event) {

    }
}
