package Facturas;

import java.io.IOException;
import java.net.URL;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedList;
import java.util.ResourceBundle;

import BaseDatos.Datos;
import Cliente.Clientes;
import Producto.Operaciones;
import Producto.Productos;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Cell;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;
import javafx.scene.control.TableColumn.CellDataFeatures;

/**Clase de el controlador de la ventana registrar factura
 * 
 * 
 *
 */
public class ventanaRegistrarFacturaController implements Initializable{
	@FXML
	private TextField codigoProductoTxt;
	@FXML
    private TextField cantidadTxt;
	@FXML
	private TextField nombreTxt;
	@FXML
	private TextField apellidoTxt;
	@FXML
	private TextField identificacionTxt;
	@FXML
	private TextField telefonoTxt;
	 @FXML
	private TextField direccionTxt;
	@FXML
    private TextField credencialVendedorTxt;
	@FXML
	private TableView<Productos> registrarVentaTable;
	@FXML
	private TableColumn<Productos, Float> ivaColumn;
	@FXML
	private TableColumn<Productos, String> referenciaColumn;
	@FXML
	private TableColumn<Productos, String> tipoProductoColumn;
	@FXML
	private TableColumn<Productos, String> tipoJuegoColumn;
	@FXML
	private TableColumn<Productos, String> nombreProductoColumn;
	@FXML
	private TableColumn<Productos, String> plataformaColumn;
	@FXML
	private TableColumn<Productos, String> precioColumn;
	@FXML
	private TableColumn<Productos, Float> impuestoColumn;
	@FXML
	private TableColumn<Productos, Float> valorColumn;
	@FXML
	private TableColumn<?, ?> cantidadColumn;
	 @FXML
	private TableColumn<?, ?> totalColumn;
	@FXML
	private Button ingresarBtn;
	@FXML
	private Button regresarBtn;
	@FXML
	private CheckBox descuentoBox;
	@FXML
	private Button generarFacturaBtn;
	@FXML
    private Label valorTotalLabel;
	
	private Datos dataProvider = new Datos();
	private Datos dataProvider1 = new Datos();
	private ObservableList<Productos> data = FXCollections.observableArrayList();
	
	private float id; 
	private String fecha;
	private float subtotal;
	private float valorTotal;
	private float descuento = 0;
	private String crendencialVendedor;
	private String identificacionCliente;
	private Float idFac = null;
	
	Productos producto;
	
	// Event Listener on TableView[#registrarVentaTable].onMouseClicked
	@FXML
	public void onSelection(MouseEvent event) {
		// TODO Autogenerated
		descuento =  (float) 0.2; 
	}
	
	

	// Event Listener on Button[#ingresarBtn].onMouseClicked
	/**Metodo que muestra los datos del producto
	 * 
	 * @param event
	 */
	@FXML
	public void onIngresarClicked(MouseEvent event) {
		Productos producto = dataProvider.consultarProducto(codigoProductoTxt.getText());
		
		try {
		    if (producto.getReferencia() != null) {
		        this.data.add(producto); // Agregar el producto a la lista
		        
		        String cantidadString = cantidadTxt.getText();
		        
		        int cantidad = Integer.parseInt(cantidadString);//cambia el valor de cantidad de tipo String a tipo int
		        
		        Operaciones op = new Operaciones();
		        float totalProducto = op.total();
		        
		        totalProducto = (totalProducto*cantidad);//- (totalProducto*descuento);
		        
		        
		        		        
		        cantidadColumn.setCellValueFactory(new PropertyValueFactory<>("cantidad")); //agrego el valor de cantidad a la columna cantidad
		        totalColumn.setCellValueFactory(new PropertyValueFactory<>("total"));
		        for (Productos prod : data) {
		            prod.setCantidad(cantidad);
		            prod.setTotal(totalProducto); // Establecer la cantidad en el objeto Producto
		        }
		        
		        
		        
		        this.registrarVentaTable.setItems(data); // Asignar la lista a la TableView para que se muestren los datos
		    	}
			}
		 catch (Exception e) {
			 Alert alt = new Alert(AlertType.ERROR);
				alt.setContentText("Error ");
				alt.setHeaderText("Producto no encontrado");
				alt.show();
			}
	}
	
	
	
	
	// Event Listener on Button[#regresarBtn].onMouseClicked
	@FXML
	public void onRegresarClicked(MouseEvent event) {
		Parent root = null;
	    try {
	        root = FXMLLoader.load(getClass().getResource("/Presentacion/ventanaOpcionesVendedor.fxml"));
	        Scene scene = new Scene(root);
	        
	        // Obtén el escenario actual usando el evento
	        Stage currentStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
	        
	        // Configura el nuevo escenario
	        Stage newStage = new Stage();
	        newStage.setScene(scene);
	        
	        //Agregar titulo a la ventana
	        newStage.setTitle("WowGames: VentanaOpciones");
	        
	        // Muestra el nuevo escenario
	        newStage.show();
	        
	        // Cierra el escenario actual
	        currentStage.close();
	        
	    } catch (IOException e) {
	        // TODO Auto-generated catch block
	        e.printStackTrace();
	    }
		
		// TODO Autogenerated
	}
	
	
	
	// Event Listener on Button[#generarFacturaBtn].onMouseClicked
	/**Metodo que genera el id de las facturas automaticamente, calcula la fecha actual y calcula el subtotal de la factura
	 * 
	 * @param event
	 */
	@FXML
	public void onGenerarClicked(MouseEvent event) {		

		//se genera automaticamente el ID de cada factura
	if(idFac == null) {
				idFac = (float) 1;
			}else {
				Datos datos = new Datos(); 
		        Facturas resultado = null;
		        resultado = datos.consultarId(resultado);
		        
		        idFac = resultado.getId() + 1; 
			}
		
		//se calcula la fecha
		LocalDate fechaActual = LocalDate.now();
    	DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy");
	    String fecha = fechaActual.format(formato);
		
	    //se calcula el subtotal
	    
	    
	    
	    
	    
	    
	    
		Facturas nuevo = new Facturas(idFac, fecha, subtotal, valorTotal,descuento, crendencialVendedor, identificacionCliente );
		boolean success = this.dataProvider.createFactura(nuevo);
		if (success) {
			Alert alt = new Alert(Alert.AlertType.INFORMATION);
			alt.setContentText("Factura Creada");
			alt.setHeaderText("Creado");
			alt.show();
		}else {
			Alert alt = new Alert(Alert.AlertType.ERROR);
			alt.setContentText("Error al crear el factura");
			alt.setHeaderText("Error");
			alt.show();
		}
		
		
	}
	
	
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		this.referenciaColumn.setCellValueFactory(new PropertyValueFactory<Productos, String>("referencia"));
		this.ivaColumn.setCellValueFactory(new PropertyValueFactory<Productos, Float>("iva"));
		this.tipoProductoColumn.setCellValueFactory(new PropertyValueFactory<Productos, String>("tipoProducto"));
		this.tipoJuegoColumn.setCellValueFactory(new PropertyValueFactory<Productos, String>("tipoJuego"));
		this.nombreProductoColumn.setCellValueFactory(new PropertyValueFactory<Productos, String>("nombre"));
		this.valorColumn.setCellValueFactory(new PropertyValueFactory<Productos, Float>("valorUnitario"));
		this.impuestoColumn.setCellValueFactory(new PropertyValueFactory<Productos, Float>("impuesto"));
		this.plataformaColumn.setCellValueFactory(new PropertyValueFactory<Productos, String>("plataforma"));
		this.cantidadColumn.setCellValueFactory(new PropertyValueFactory< >("cantidad"));
		this.totalColumn.setCellValueFactory(new PropertyValueFactory< >("total"));
		
		
	}
}
